# docker-compose.yml

version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

    volumes:
      - .:/app
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      - db
#      - tests
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}

  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 100

  networks:
    app_network:
      name: app_network
      driver: bridge