version: '3.8'

services:
  test_web_app:
    container_name: test_web_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "pytest -vv"
    networks:
      - app_test_network


networks:
  app_test_network:
    external:
      name: app_network
