# docker-compose.yml

version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
#    environment:
#      - DB_HOST=postgres_db
#      - DB_NAME=ylabproject
#      - DB_USER=postgres
#      - DB_PASS=root
    entrypoint: >
      sh -c "
        alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/app
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
          condition: service_healthy



  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
#    env_file:
#      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 100
    restart: always

networks:
  app_network:
    name: app_network